### ISSUE TITLE
Thread class causes downstream problems

### ISSUE THREAD

**Issue by Jaymon** [Jaymon/testdata#20]
In one testsuite, using `testdata.threading.Thread` when (I think) a `KeyboardInterrupt` was triggered.

After the test that triggered the `KeyboardInterrupt`, another test used `subprocess` (both `check_output` and `check_call`) and it would stall (specifically I was using `testdata.service.InitD.restart` after switching some raw calls to use `testdata.service` classes) and dump the `KeyboardInterrupt`.

This is the stacktrace:

```
Starting tests.interface.postgres_test.InterfacePGBouncerTest.test_db_disconnect
Stopping tests.interface.postgres_test.InterfacePGBouncerTest.test_db_disconnect after 3.28s
Traceback (most recent call last):
  File "/usr/local/bin/pyt", line 11, in <module>
    sys.exit(console())
  File "/usr/local/lib/python2.7/dist-packages/pyt/__main__.py", line 49, in console
    argv=test_args,
  File "/usr/local/lib/python2.7/dist-packages/pyt/tester.py", line 576, in run_test
    ret = unittest.main(**kwargs)
  File "/usr/lib/python2.7/unittest/main.py", line 95, in __init__
    self.runTests()
  File "/usr/lib/python2.7/unittest/main.py", line 232, in runTests
    self.result = testRunner.run(self.test)
  File "/usr/local/lib/python2.7/dist-packages/pyt/tester.py", line 550, in run
    result = super(TestRunner, self).run(test)
  File "/usr/lib/python2.7/unittest/runner.py", line 151, in run
    test(result)
  File "/usr/lib/python2.7/unittest/suite.py", line 70, in __call__
    return self.run(*args, **kwds)
  File "/usr/lib/python2.7/unittest/suite.py", line 108, in run
    test(result)
  File "/usr/lib/python2.7/unittest/suite.py", line 70, in __call__
    return self.run(*args, **kwds)
  File "/usr/lib/python2.7/unittest/suite.py", line 108, in run
    test(result)
  File "/usr/lib/python2.7/unittest/suite.py", line 70, in __call__
    return self.run(*args, **kwds)
  File "/usr/lib/python2.7/unittest/suite.py", line 108, in run
    test(result)
  File "/usr/lib/python2.7/unittest/suite.py", line 70, in __call__
    return self.run(*args, **kwds)
  File "/usr/lib/python2.7/unittest/suite.py", line 108, in run
    test(result)
  File "/usr/lib/python2.7/unittest/case.py", line 395, in __call__
    return self.run(*args, **kwds)
  File "/usr/lib/python2.7/unittest/case.py", line 331, in run
    testMethod()
  File "/vagrant/tests/interface/postgres_test.py", line 93, in test_db_disconnect
    InitD("postgresql").restart()
  File "/usr/local/lib/python2.7/dist-packages/testdata/service.py", line 34, in restart
    self.start()
  File "/usr/local/lib/python2.7/dist-packages/testdata/service.py", line 30, in start
    self.run(cmd, kwargs)
  File "/usr/local/lib/python2.7/dist-packages/testdata/service.py", line 42, in run
    ret = subprocess.check_output(cmd, **kwargs)
  File "/usr/lib/python2.7/subprocess.py", line 567, in check_output
    output, unused_err = process.communicate()
  File "/usr/lib/python2.7/subprocess.py", line 791, in communicate
    stdout = _eintr_retry_call(self.stdout.read)
  File "/usr/lib/python2.7/subprocess.py", line 476, in _eintr_retry_call
    return func(*args)
KeyboardInterrupt
```

The fix was to switch back to vanilla `from threading import Thread` instead of `from testdata.threading import Thread`.

This only happened when running the whole suite, I could run the tests individually (after restarting postgres and pgbouncer because the failure left them in a bad state) and they would run just fine.

**Comment by Jaymon** [comment]
It doesn't look like there is anything I can do about this, even in python 3.7 there just isn't a good way to automatically notify the main thread that there was an exception in a child thread, my best hope was:

> Python register shutdown function and then modify the thread's __new__ function to add to global threads list, and then in the register shutdown function go through and check to see if they had an error and then raise the error if they did

but that just raises the error and prints it out, it doesn't cause a test to fail or the CLI program to exit with >0 so when running all the tests a person won't get notified the test failed. Even though you can't recover from a `KeyboardInterrupt` I think it is still the best approach since it at least gives the user notification the test failed.
