### ISSUE TITLE
Python 3 running all tests is stalling on some threading issue

### ISSUE THREAD

**Issue by Jaymon** [Jaymon/testdata#53]
$ pyt3 -d

Finished all the tests and then hung, when I ctrl-c quit it returned with:

```
^CException ignored in: <module 'threading' from '/usr/local/Cellar/python/3.7.4/Frameworks/Python.framework/Versions/3.7/lib/python3.7/threading.py'>
Traceback (most recent call last):
  File "/usr/local/Cellar/python/3.7.4/Frameworks/Python.framework/Versions/3.7/lib/python3.7/threading.py", line 1308, in _shutdown
    lock.acquire()
KeyboardInterrupt
```

**Comment by Jaymon** [comment]
This stalls:

     $ pyt3 testdata_test.ThreadTest.test_raise_error_join

**Comment by Jaymon** [comment]
Looks to be a lock not getting released when join reraises an error, this is what is reported:

```
Exception ignored in: <module 'threading' from '/.../3.7.4/.../3.7/lib/python3.7/threading.py'>
Traceback (most recent call last):
  File "/.../3.7.4/.../3.7/lib/python3.7/threading.py", line 1308, in _shutdown
    lock.acquire()
```
